# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7XCYCapLCUgbKXy-x4S0whMoxiVFq2n
"""

col_names = ['과목번호', '과목명', '강의실', '시간수']
list1 = list([['C1', '인공지능개론', 'R1', 3],
              ['C2', '웃음치료', 'R2', 2],
              ['C3', '경영학', 'R3', 3],
              ['C4', '3D디자인', 'R4', 4],
              ['C5', '스포츠경영', 'R2', 2],
              ['C6', '예술의 세계', 'R3', 1]
              ])

import pandas as pd
df = pd.DataFrame(list1, columns = col_names)
df.to_csv('./timetable.csv', header = True, index = False, encoding = 'utf-8')

df2 = pd.read_csv('./timetable.csv', sep = ',')
df2['교수'] = ['김예희', '오정현', '인세훈', '이세봄', '배유진', '이가원']
df2

max_hour = df2.groupby(by=['강의실'], as_index = False)['시간수'].max( )
max_hour

import pandas as pd
import matplotlib.pyplot as plt

# CSV 파일 불러오기
file_path = "2020-2025아파트 매매.csv"
df = pd.read_csv(file_path, encoding='cp949')

# Create a time period column
df["Period"] = df["년도"].astype(str) + "Q" + df["분기"].astype(str)

# Plot the graph
plt.figure(figsize=(12, 6))
plt.plot(df["Period"], df["평균 매매가"], marker='o', linestyle='-', color='b', label="Average Price")

# Graph style settings
plt.xticks(rotation=45)  # Rotate x-axis labels
plt.xlabel("Period")
plt.ylabel("Average Price (in 10,000 KRW)")
plt.title("Seoul Apartment Trend Price (2020-2025)")
plt.legend()
plt.grid()

# Show the graph
plt.show()