# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Pp1rgI05EmvEB9vXccU0BoNrp2xRhCM
"""

a = 5
for i in range(1,10,+2):
  print(str(a) + ' X ' + str(i) + ' = ' + str(i*a))
#print('while 조건문을 for 조건문으로 바꾸어 사용할 수 있다!')

n = int(input())
a = '*'
for i in range(1,n+1):
  print(a * i)