# -*- coding: utf-8 -*-
"""python - 연산자

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8T5hsceA8LqZdljPq_JVzJo1uEkr_Wf
"""

PI = 3.14
area = 5.5 * 5.5 * PI
print(area)

A = 10 * 4 * (1/2)
B = 9 * 5 * (1/2)
print (A == B)

sci = (92 * 4) - 95 - 88 - 90
print(sci)
