# -*- coding: utf-8 -*-
"""python - 구구단

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8T5hsceA8LqZdljPq_JVzJo1uEkr_Wf
"""

a = 1

while a < 10:
    i = 1
    if a % 2 == 1:
      i = 1
    else:
      i = 2
    while i < 10:
        print(str(a) + ' X ' + str(i) + ' = ' + str(i*a))
        i += 2
    a += 1