# -*- coding: utf-8 -*-
"""python - 구구단

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8T5hsceA8LqZdljPq_JVzJo1uEkr_Wf
"""
//홀수
i = 1

while i < 10:
    j = 1
    while j < 10:
        print(str(i) + 'X' + str(j) + '=' + str(i * j))
        j += 2
    i += 2 

//짝수
i = 2

while i < 10:
    j = 2
    while j < 10:
        print(str(i) + 'X' + str(j) + '=' + str(i * j))
        j += 2
    i += 2 
