# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Pp1rgI05EmvEB9vXccU0BoNrp2xRhCM
"""

a = 5
for i in range(1,10,+2):
  print(str(a) + ' X ' + str(i) + ' = ' + str(i*a))
#print('while 조건문을 for 조건문으로 바꾸어 사용할 수 있다!')

n = int(input())
a = '*'
for i in range(1,n+1):
  print(a * i)

while True:
  try:
    print('음료목록 1.오렌지주스(100원), 2.커피(200원), 3.콜라(300원)')

    coin = int(input('동전을 넣으세요.'))

    if coin <= 0:
      print('유효하지 않은 동전입니다.')
      continue

    drink = int(input('음료를 고르세요.\n'))

    if drink == 1:
    #오렌지주스 100원
      if coin >= 100:
          remain = coin - 100
          print('오렌지주스가 곧 제공됩니다.')
          print('거스름돈은 {}원입니다.'.format(remain))
      else:
          print('잔액이 부족합니다.')

    elif drink == 2:
    #커피 200원
      if coin >= 200:
        remain = coin - 200
        print('커피가 곧 제공됩니다.')
        print('거스름돈은 {}원입니다.'.format(remain))
      else:
        print('잔액이 부족합니다.')

    elif drink == 3:
    #콜라 300원
      if coin >= 300:
        remain = coin - 300
        print('콜라가 곧 제공됩니다.')
        print('거스름돈은 {}원입니다.'.format(remain))
      else:
        print('잔액이 부족합니다.')

    else:
  #없는 번호
     print('없는 메뉴입니다. 다시 입력해 주세요.')

  except ValueError:
        print("다시 입력해주세요.")

while True:
    try:
        n = int(input("숫자를 입력하세요: "))
        if n <= 0:
            print("다시 입력해주세요.")
        else:
            a = ' * '
            for i in range(1, n + 1):
                print(a * i)
            break
    except ValueError:
        print("다시 입력해주세요.")

while True:
    try:
        n = int(input("1부터 9 사이의 숫자를 입력하세요: "))
        if n < 1 or n > 9:
            print("1부터 9 사이의 숫자를 입력해주세요.")
        else:
            count = 0
            star_distribution = [1, 3, 5]

            for i in range(3):
                stars = ''
                for j in range(star_distribution[i]):
                    if count < n:
                        stars += '*'
                        count += 1
                    else:
                        stars += ' '
                print(stars.center(5))
            break
    except ValueError:
        print("정수를 입력해주세요.")